# Generated by Django 2.2.1 on 2019-09-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_good',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
