# Generated by Django 2.2.1 on 2019-06-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cause',
            field=models.CharField(choices=[('0', 'Перемещение'), ('1', 'Производство'), ('2', 'Списание')], default='0', max_length=20),
        ),
    ]
