# Generated by Django 2.2.1 on 2019-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190909_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_good',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
