# Generated by Django 2.2.1 on 2021-03-06 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190909_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Основание', 'verbose_name_plural': 'Основания'},
        ),
        migrations.AlterModelOptions(
            name='counter_stock',
            options={'verbose_name': 'Склад контрагента', 'verbose_name_plural': 'Склады контрагентов'},
        ),
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='default_number',
            options={'verbose_name': 'Число по умолчанию', 'verbose_name_plural': 'Числа по умолчанию'},
        ),
        migrations.AlterModelOptions(
            name='default_text',
            options={'verbose_name': 'Текст по умолчанию', 'verbose_name_plural': 'Тексты по умолчанию'},
        ),
        migrations.AlterModelOptions(
            name='default_var',
            options={'verbose_name': 'Значение по умолчанию', 'verbose_name_plural': 'Значения по умолчанию'},
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={'verbose_name': 'Требование', 'verbose_name_plural': 'Требования'},
        ),
        migrations.AlterModelOptions(
            name='demand_good',
            options={'verbose_name': 'Товар требования', 'verbose_name_plural': 'Товары требований'},
        ),
        migrations.AlterModelOptions(
            name='good_name',
            options={'verbose_name': 'Имя товара', 'verbose_name_plural': 'Имена товаров'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goods_property',
            options={'verbose_name': 'Свойство товара', 'verbose_name_plural': 'Свойства товаров'},
        ),
        migrations.AlterModelOptions(
            name='goods_string',
            options={'verbose_name': 'Текстовые свойства товаров', 'verbose_name_plural': 'Текстовое свойство товара'},
        ),
        migrations.AlterModelOptions(
            name='goods_unit',
            options={'verbose_name': 'Единица измерения товара', 'verbose_name_plural': 'Единицы измерения товаров'},
        ),
        migrations.AlterModelOptions(
            name='goods_var',
            options={'verbose_name': 'Вариант свойства товара', 'verbose_name_plural': 'Варианты свойств товаров'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Инвентаризация', 'verbose_name_plural': 'Инвентаризации'},
        ),
        migrations.AlterModelOptions(
            name='inventory_good',
            options={'verbose_name': 'Товар инвентаризации', 'verbose_name_plural': 'Товары инвентаризаций'},
        ),
        migrations.AlterModelOptions(
            name='matrix',
            options={'verbose_name': 'Матрица', 'verbose_name_plural': 'Матрицы'},
        ),
        migrations.AlterModelOptions(
            name='model_group',
            options={'verbose_name': 'Группа модели', 'verbose_name_plural': 'Группы моделей'},
        ),
        migrations.AlterModelOptions(
            name='model_property',
            options={'verbose_name': 'Свойство модели', 'verbose_name_plural': 'Свойства моделей'},
        ),
        migrations.AlterModelOptions(
            name='model_unit',
            options={'verbose_name': 'Единица измерения модели', 'verbose_name_plural': 'Единицы измерения моделей'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордеры'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='product_model',
            options={'verbose_name': 'Модель товара', 'verbose_name_plural': 'Модели товаров'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.AlterModelOptions(
            name='property_num',
            options={'verbose_name': 'Числовое свойство товара', 'verbose_name_plural': 'Числовые свойства товаров'},
        ),
        migrations.AlterModelOptions(
            name='property_range',
            options={'verbose_name': 'Диапазон свойства', 'verbose_name_plural': 'Диапазоны свойств'},
        ),
        migrations.AlterModelOptions(
            name='property_var',
            options={'verbose_name': 'Вариант свойства', 'verbose_name_plural': 'Варианты свойств'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='stock_good',
            options={'verbose_name': 'Товар на складе', 'verbose_name_plural': 'Товары на складах'},
        ),
        migrations.AlterModelOptions(
            name='stock_operation',
            options={'ordering': ['-date'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Журнал операций'},
        ),
        migrations.AlterModelOptions(
            name='user_group',
            options={'verbose_name': 'Пользовательская группа', 'verbose_name_plural': 'Пользовательские группы'},
        ),
        migrations.AlterModelOptions(
            name='user_permission',
            options={'verbose_name': 'Пользовательское разрешение', 'verbose_name_plural': 'Пользовательские разрешения'},
        ),
        migrations.AlterField(
            model_name='base',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='counter_stock',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='counter_stock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='cur_vin',
            field=models.IntegerField(blank=True, default='0', verbose_name='Текущий ВИН'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='is_consumer',
            field=models.BooleanField(verbose_name='Потребитель'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='is_member',
            field=models.BooleanField(verbose_name='Член группы'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='is_provider',
            field=models.BooleanField(verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='kind',
            field=models.CharField(choices=[('0', 'Организация'), ('1', 'Физлицо'), ('2', 'Административная группа')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(max_length=200, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='default_number',
            name='number',
            field=models.FloatField(verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='default_text',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='default_var',
            name='var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property_var', verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='acceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to='stock.Stock', verbose_name='Акцептор'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='stock.Counterparty', verbose_name='Потребитель'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='stock.Stock', verbose_name='Донор'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_demand',
            field=models.BooleanField(default=True, verbose_name='Требование'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Matrix', verbose_name='Матрица'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='stock.Counterparty', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Дата отпуска'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='vin',
            field=models.IntegerField(blank=True, verbose_name='ВИН'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='article',
            field=models.CharField(default='-', max_length=200, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Matrix', verbose_name='Матрица'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='demand_good',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Unit', verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='good_name',
            name='area',
            field=models.CharField(choices=[('0', 'Локальное'), ('1', 'Транзитное'), ('2', 'Оригинальное')], max_length=20, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='good_name',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='good_name',
            name='name_type',
            field=models.CharField(choices=[('1', 'Артикул'), ('0', 'Наименование'), ('2', 'Штрихкод')], max_length=20, verbose_name='Тип имени'),
        ),
        migrations.AlterField(
            model_name='good_name',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product_model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='producer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Counterparty', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='goods_property',
            name='applicable',
            field=models.BooleanField(verbose_name='Применимое'),
        ),
        migrations.AlterField(
            model_name='goods_property',
            name='editable',
            field=models.BooleanField(verbose_name='Изменяемое'),
        ),
        migrations.AlterField(
            model_name='goods_property',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='goods_property',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='goods_property',
            name='visible',
            field=models.BooleanField(verbose_name='Видимое'),
        ),
        migrations.AlterField(
            model_name='goods_string',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='goods_unit',
            name='applicable',
            field=models.BooleanField(verbose_name='Применимая'),
        ),
        migrations.AlterField(
            model_name='goods_unit',
            name='coeff',
            field=models.FloatField(verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='goods_unit',
            name='isBase',
            field=models.BooleanField(verbose_name='Базова'),
        ),
        migrations.AlterField(
            model_name='goods_unit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='goods_unit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Unit', verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='goods_var',
            name='var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property_var', verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='is_finished',
            field=models.BooleanField(verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='inventory_good',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='inventory_good',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='inventory_good',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory', verbose_name='Инвентаризация'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='access',
            field=models.CharField(choices=[('0', 'Открыто всем'), ('1', 'Открыто донору'), ('2', 'Открыто акцептору'), ('3', 'Закрыто'), ('4', 'Выполнение')], default='0', max_length=20, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='cause',
            field=models.CharField(choices=[('0', 'Перемещение'), ('1', 'Оприходование/Выбытие'), ('2', 'Инвентаризация')], default='0', max_length=20, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='cause_id',
            field=models.IntegerField(default=0, null=True, verbose_name='id операции'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='model_group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='model_group',
            name='parent',
            field=models.IntegerField(null=True, verbose_name='Родительская группа'),
        ),
        migrations.AlterField(
            model_name='model_property',
            name='editable',
            field=models.BooleanField(verbose_name='Изменяемое'),
        ),
        migrations.AlterField(
            model_name='model_property',
            name='isDefault',
            field=models.BooleanField(verbose_name='Значение по умолчанию?'),
        ),
        migrations.AlterField(
            model_name='model_property',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product_model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='model_property',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='model_property',
            name='visible',
            field=models.BooleanField(verbose_name='Видимое'),
        ),
        migrations.AlterField(
            model_name='model_unit',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product_model', verbose_name='Модель товара'),
        ),
        migrations.AlterField(
            model_name='model_unit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cause',
            field=models.CharField(choices=[('0', 'Перемещение'), ('1', 'Производство'), ('2', 'Списание'), ('3', 'Поступление')], default='0', max_length=20, verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isDonor',
            field=models.BooleanField(verbose_name='Донор?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Matrix', verbose_name='Матрица'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Свободно'), ('1', 'Заполнение'), ('2', 'Завершено')], default='0', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='package',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Matrix', verbose_name='Матрица'),
        ),
        migrations.AlterField(
            model_name='package',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='package',
            name='vin',
            field=models.IntegerField(blank=True, verbose_name='ВИН'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Model_group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_type',
            field=models.PositiveSmallIntegerField(verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='property_num',
            name='number',
            field=models.FloatField(verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='property_range',
            name='inf',
            field=models.FloatField(verbose_name='Минимум'),
        ),
        migrations.AlterField(
            model_name='property_range',
            name='sup',
            field=models.FloatField(verbose_name='Максимум'),
        ),
        migrations.AlterField(
            model_name='property_var',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='property_var',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cur_vin',
            field=models.IntegerField(default='0', verbose_name='Текущий ВИН'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='stock_good',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stock_good',
            name='cost',
            field=models.FloatField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='stock_good',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stock_good',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='stock_good',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Unit', verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='cost',
            field=models.FloatField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='last_value',
            field=models.FloatField(blank=True, default=0, verbose_name='Последнее значение'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='operation',
            field=models.CharField(choices=[('0', 'Приход'), ('1', 'Расход'), ('2', 'Коррекция')], default='0', max_length=20, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Package', verbose_name='Пакет'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Unit', verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Counterparty', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user_permission',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='Разрешено'),
        ),
        migrations.AlterField(
            model_name='user_permission',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Section', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='user_permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
