# Generated by Django 2.2.1 on 2019-06-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_demand_good_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Goods')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Inventory')),
            ],
        ),
    ]
