# Generated by Django 2.2.1 on 2019-08-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_inventory_inventory_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-pk']},
        ),
    ]
