# Generated by Django 2.2.1 on 2021-08-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210306_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('value', models.FloatField(default='0', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Константа',
                'verbose_name_plural': 'Константы',
            },
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Проекция',
                'verbose_name_plural': 'Проекции',
            },
        ),
        migrations.CreateModel(
            name='Projection_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Projection', verbose_name='Проекция')),
                ('property_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Property_var', verbose_name='Вариант свойства')),
            ],
            options={
                'verbose_name': 'Значение проекции',
                'verbose_name_plural': 'Значения проекций',
            },
        ),
    ]
