# Generated by Django 2.2.1 on 2021-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_constant_projection_projection_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_good',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='stock_operation',
            name='operation',
            field=models.CharField(choices=[('1', 'Расход'), ('0', 'Приход'), ('2', 'Коррекция')], default='0', max_length=20, verbose_name='Операция'),
        ),
    ]
