# Generated by Django 2.2.1 on 2019-08-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190827_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-date']},
        ),
    ]
