# Generated by Django 2.2.1 on 2019-08-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190827_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={},
        ),
    ]
