# Generated by Django 2.2.3 on 2019-09-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190829_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_good',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
