# Generated by Django 2.2.1 on 2019-06-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Packing_divergence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amm', models.FloatField()),
                ('pack_amm', models.FloatField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('prod_num', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Product')),
                ('reactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Reactor')),
                ('tank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Tank')),
            ],
        ),
        migrations.CreateModel(
            name='Packaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Movement_rec')),
            ],
        ),
        migrations.AddField(
            model_name='movement_rec',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Operation'),
        ),
        migrations.AddField(
            model_name='movement_rec',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Product'),
        ),
        migrations.CreateModel(
            name='Material_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Movement_rec')),
            ],
        ),
    ]
