# Generated by Django 2.2.1 on 2019-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing_divergence',
            name='pack_amm_set',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
