# Generated by Django 2.2.1 on 2021-03-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_packing_char'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptance',
            options={'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
        migrations.AlterModelOptions(
            name='movement_rec',
            options={'verbose_name': 'Запись о перемещении', 'verbose_name_plural': 'Записи о перемещении'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='packaged',
            options={'verbose_name': 'Фасовка', 'verbose_name_plural': 'Фасовки'},
        ),
        migrations.AlterModelOptions(
            name='packing_char',
            options={'verbose_name': 'Числовая характеристика фасовки', 'verbose_name_plural': 'Числовые характеристики фасовок'},
        ),
        migrations.AlterModelOptions(
            name='packing_divergence',
            options={'verbose_name': 'Разница в фасовке', 'verbose_name_plural': 'Разница в фасовке'},
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='code',
            field=models.IntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Movement_rec', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='material_log',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='material_log',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='material_log',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Material', verbose_name='Реактив'),
        ),
        migrations.AlterField(
            model_name='movement_rec',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='movement_rec',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='movement_rec',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='movement_rec',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Напечатан паспорт?'),
        ),
        migrations.AlterField(
            model_name='movement_rec',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Operation', verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='movement_rec',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='packaged',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='packaged',
            name='rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Movement_rec', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='packing_char',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading_char_number', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='packing_char',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Packing_divergence', verbose_name='Фасовка'),
        ),
        migrations.AlterField(
            model_name='packing_char',
            name='value',
            field=models.FloatField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='pack_amm',
            field=models.FloatField(verbose_name='Фасуемое количество'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='pack_amm_set',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Множество фасуемых объёмов'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='prod_num',
            field=models.FloatField(verbose_name='Количество продуктов'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='reactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Reactor', verbose_name='Реактор'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='start_amm',
            field=models.FloatField(verbose_name='Начальное количество'),
        ),
        migrations.AlterField(
            model_name='packing_divergence',
            name='tank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Tank', verbose_name='Танк'),
        ),
    ]
