# Generated by Django 2.2.1 on 2021-03-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterModelOptions(
            name='batch_comp',
            options={'verbose_name': 'Компонент партии', 'verbose_name_plural': 'Компоненты партий'},
        ),
        migrations.AlterModelOptions(
            name='kneading',
            options={'verbose_name': 'Процесс смешения', 'verbose_name_plural': 'Процессы смешения'},
        ),
        migrations.AlterModelOptions(
            name='kneading_char',
            options={'verbose_name': 'Характеристика процесса', 'verbose_name_plural': 'Характеристики процессов'},
        ),
        migrations.AlterModelOptions(
            name='kneading_char_number',
            options={'verbose_name': 'Числовая характеристика партии', 'verbose_name_plural': 'Числовые характеристики партий'},
        ),
        migrations.AlterModelOptions(
            name='kneading_char_var',
            options={'verbose_name': 'Вариант характеристики партии', 'verbose_name_plural': 'Варианты характеристик партий'},
        ),
        migrations.AlterModelOptions(
            name='list_component',
            options={'verbose_name': 'Компонент загрузочного листа', 'verbose_name_plural': 'Компоненты загрузочных листов'},
        ),
        migrations.AlterModelOptions(
            name='loading_list',
            options={'verbose_name': 'Загрузочный лист', 'verbose_name_plural': 'Загрузочные листы'},
        ),
        migrations.AlterModelOptions(
            name='model_component',
            options={'verbose_name': 'Компонент модели загрузочного листа', 'verbose_name_plural': 'Компоненты моделей загрузочных листов'},
        ),
        migrations.AlterModelOptions(
            name='model_list',
            options={'verbose_name': 'Модель загрузочного листа', 'verbose_name_plural': 'Модели загрузочных листов'},
        ),
        migrations.AlterModelOptions(
            name='month_plan',
            options={'verbose_name': 'План на месяц', 'verbose_name_plural': 'Планы на месяц'},
        ),
        migrations.AlterModelOptions(
            name='pack_process',
            options={'verbose_name': 'Процесс фасовки', 'verbose_name_plural': 'Процессы фасовки'},
        ),
        migrations.AlterModelOptions(
            name='reactor_content',
            options={'verbose_name': 'Содержимое реактора', 'verbose_name_plural': 'Содержимое реакторов'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='state_log',
            options={'verbose_name': 'Лог процесса', 'verbose_name_plural': 'Логи процессов'},
        ),
        migrations.AlterModelOptions(
            name='tank_content',
            options={'verbose_name': 'Содержимое танка', 'verbose_name_plural': 'Содержимое танков'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='finish_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='kneading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading', verbose_name='Процесс смешения'),
        ),
        migrations.AlterField(
            model_name='batch_comp',
            name='ammount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='batch_comp',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='batch_comp',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Material', verbose_name='Реактив'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='batch_num',
            field=models.FloatField(default=0, verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='finish_date',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='isFinished',
            field=models.BooleanField(default=False, verbose_name='Завершён?'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='isValid',
            field=models.BooleanField(default=False, verbose_name='Соответствует контролю качества?'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Loading_list', verbose_name='Загрузочный лист'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Reactor', verbose_name='Реактор'),
        ),
        migrations.AlterField(
            model_name='kneading',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='kneading_char',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Characteristic', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='kneading_char',
            name='kneading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading', verbose_name='Процесс'),
        ),
        migrations.AlterField(
            model_name='kneading_char_number',
            name='number',
            field=models.FloatField(verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='kneading_char_var',
            name='char_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Set_var', verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='kneading_char_var',
            name='kneading_char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading_char', verbose_name='Характеристика партии'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='ammount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='compl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Compl_comp', verbose_name='Существующая технологическая композиция'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Formula', verbose_name='Технологическая композиция собственного производства'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Loading_list', verbose_name='Загрузочный лист'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='loaded',
            field=models.BooleanField(default=False, verbose_name='Загружена?'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='mat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Material', verbose_name='Реактив'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимум'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Минимум'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='r_cont',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Reactor_content', verbose_name='Композиция из реактора'),
        ),
        migrations.AlterField(
            model_name='list_component',
            name='t_cont',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Tank_content', verbose_name='Композиция из танка'),
        ),
        migrations.AlterField(
            model_name='loading_list',
            name='ammount',
            field=models.FloatField(verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='loading_list',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Formula', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='model_component',
            name='ammount',
            field=models.FloatField(verbose_name='Количество, %'),
        ),
        migrations.AlterField(
            model_name='model_component',
            name='formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Formula', verbose_name='Составной компонент'),
        ),
        migrations.AlterField(
            model_name='model_component',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Model_list', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='model_component',
            name='mat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Material', verbose_name='Реактив'),
        ),
        migrations.AlterField(
            model_name='model_list',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Formula', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='month',
            field=models.CharField(max_length=10, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='num',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='pack_process',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='pack_process',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pack_process',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершено?'),
        ),
        migrations.AlterField(
            model_name='pack_process',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='pack_process',
            name='reactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Reactor', verbose_name='Реактор'),
        ),
        migrations.AlterField(
            model_name='pack_process',
            name='tank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Tank', verbose_name='Танк'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='batch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='content_type',
            field=models.FloatField(default=3, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='kneading',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading', verbose_name='Процесс смешения'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Reactor', verbose_name='Реактор'),
        ),
        migrations.AlterField(
            model_name='reactor_content',
            name='reserved',
            field=models.FloatField(default=0, verbose_name='Зарезервирован?'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='state_log',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='state_log',
            name='kneading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading', verbose_name='Смешение'),
        ),
        migrations.AlterField(
            model_name='state_log',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.State', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='batch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='content_type',
            field=models.FloatField(default=3, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='kneading',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.Kneading', verbose_name='Процесс смешения'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='reserved',
            field=models.FloatField(default=0, verbose_name='Зарезервировано?'),
        ),
        migrations.AlterField(
            model_name='tank_content',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Tank', verbose_name='Танк'),
        ),
    ]
