# Generated by Django 2.2.1 on 2021-08-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20210306_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_component',
            name='max',
        ),
        migrations.RemoveField(
            model_name='model_component',
            name='min',
        ),
    ]
