from django.contrib import admin
from .models import Char_group, Composition_char, Boxing_mat, Box_group, Comp_char_var, Characteristic, Characteristic_set_var, Characteristic_type, Material_group, Prefix, Unit, Material, Product_group, Product_use, Product_form, Product_option, Product_detail, Product_mark, Product, Composition_group, Container_group, Colour, Container_mat, Container, Cap_group, Cap, Boxing, Sticker_part, Sticker, Composition, Components, Production, Reactor, Tank, Formula_component, Formula

admin.site.register(Material_group)
admin.site.register(Prefix)
admin.site.register(Unit)
admin.site.register(Material)
admin.site.register(Product_group)
admin.site.register(Product_use)
admin.site.register(Product_form)
admin.site.register(Product_option)
admin.site.register(Product_detail)
admin.site.register(Product_mark)
admin.site.register(Product)
admin.site.register(Composition)
admin.site.register(Components)
admin.site.register(Composition_group)
admin.site.register(Container_group)
admin.site.register(Colour)
admin.site.register(Container_mat)
admin.site.register(Container)
admin.site.register(Cap_group)
admin.site.register(Cap)
admin.site.register(Boxing)
admin.site.register(Sticker_part)
admin.site.register(Sticker)
admin.site.register(Production)
admin.site.register(Reactor)
admin.site.register(Tank)
admin.site.register(Formula)
admin.site.register(Formula_component)
admin.site.register(Char_group)
admin.site.register(Characteristic_type)
admin.site.register(Characteristic_set_var)
admin.site.register(Characteristic)
admin.site.register(Composition_char)
admin.site.register(Comp_char_var)
admin.site.register(Boxing_mat)
admin.site.register(Box_group)

# Register your models here.
